version: '2'
services:
  monolith-db:
    image: postgres:13
    environment:
      TZ: Asiz/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres1234
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    restart: unless-stopped

  monolith:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    labels:      
      - traefik.enable=true
      - traefik.http.routers.monolith.entrypoints=web
      - traefik.http.routers.monolith.rule=Host(`monolith.localhost`)
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: broker:29092
    depends_on:
      - broker
